services:
  wallet-backend:
    image: waltid/wallet-backend:latest
    volumes:
      - ./wallet-backend/config:/waltid-web-wallet/config
      - ./wallet-backend/walt.yaml:/waltid-web-wallet/walt.yaml
  wallet-frontend:
    image: waltid/wallet-frontend:latest
    environment:
      NUXT_PUBLIC_ISSUER_CALLBACK_URL: "http://localhost:$WALLET_FRONTEND_PORT"
  issuer:
    image: waltid/issuer:latest
    volumes:
      - ./issuer/config:/waltid-issuer/config
  verifier:
    image: waltid/verifier:latest
    volumes:
      - ./verifier/config:/waltid-verifier/config
  web-portal:
    image: waltid/portal:local
    environment:
      VC_REPO: "http://localhost:$VC_REPO_PORT"
      ISSUER: "http://localhost:$ISSUER_PORT"
      VERIFIER: "http://localhost:$VERIFIER_PORT"
      WALLET: "http://localhost:$WALLET_FRONTEND_PORT"
  vc-repo:
    image: waltid/vc-repository:latest
  ingress:
    image: nginx:1.15.10-alpine
    ports:
      - target: $WALLET_FRONTEND_PORT
        published: $WALLET_FRONTEND_PORT # wallet-frontend
        protocol: tcp
        mode: host
      - target: $WEB_PORTAL_PORT
        published: $WEB_PORTAL_PORT # web-portal
        protocol: tcp
        mode: host
      - target: $VC_REPO_PORT
        published: $VC_REPO_PORT # vc-repo
        protocol: tcp
        mode: host
      - target: $ISSUER_PORT
        published: $ISSUER_PORT # issuer-api
        protocol: tcp
        mode: host
      - target: $VERIFIER_PORT
        published: $VERIFIER_PORT # verifier-api
        protocol: tcp
        mode: host
    volumes:
      - ./ingress.conf:/etc/nginx/conf.d/default.conf # API gateway configuration