services:
  walletkit:
    image: waltid/walletkit:latest  # backend docker image
    command:
      - run
    environment:
      WALTID_DATA_ROOT: /waltid-walletkit/data-root
      WALTID_WALLET_BACKEND_BIND_ADDRESS: 0.0.0.0
      WALTID_WALLET_BACKEND_PORT: "$WALLETKIT_PORT"
      EXTERNAL_HOSTNAME: $HOSTNAME
    volumes:
      - ./walletkit:/waltid-walletkit/data-root # data store volume incl. config files.
    extra_hosts:
      - "$HOSTNAME:host-gateway"
  wallet-backend:
    image: waltid/wallet-backend:latest
    volumes:
      - ./wallet-backend/config:/waltid-web-wallet/config
      - ./wallet-backend/walt.yaml:/waltid-web-wallet/walt.yaml
  wallet-frontend:
    image: waltid/wallet-frontend:latest
    environment:
      NUXT_PUBLIC_ISSUER_URL: "http://localhost:$ISSUER_PORT"
  issuer-portal:
    image: waltid/ssikit-issuer-portal:latest
  verifier-portal:
    image: waltid/ssikit-verifier-portal:latest
  ingress:
    image: nginx:1.15.10-alpine
    ports:
      - target: $WALLET_FRONTEND_PORT
        published: $WALLET_FRONTEND_PORT # wallet-frontend
        protocol: tcp
        mode: host
      - target: $ISSUER_PORT
        published: $ISSUER_PORT # issuer-portal
        protocol: tcp
        mode: host
      - target: $VERIFIER_PORT
        published: $VERIFIER_PORT # verifier-portal
        protocol: tcp
        mode: host
    volumes:
      - ./ingress.conf:/etc/nginx/conf.d/default.conf # API gateway configuration