name: Release on push to main

on:
  push:
    branches:
      - main

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Calculate release version
        run: |
          echo "release_version=1.$(date +'%g%m%d%H%M').0" >> $GITHUB_ENV
      - name: Set version
        run: |
          sed -i "s/1.SNAPSHOT/${{ env.release_version }}/g" build.gradle.kts src/main/kotlin/id/walt/Values.kt
      - run: |
          git tag v${{ env.release_version }}
          git push --tags
      - name: Setup java
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt-hotspot'
          java-version: '17'
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1
      - name: Running gradle build
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: build --no-daemon

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images (backend)
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          file: backend.Dockerfile
          tags: waltid/wallet-backend:latest, waltid/wallet-backend:${{ env.release_version }}, waltid/wallet-backend:portal-latest

      - name: Build and push Docker images (frontend)
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          file: frontend.Dockerfile
          tags: waltid/wallet-frontend:latest, waltid/wallet-frontend:${{ env.release_version }}, waltid/wallet-frontend:portal-latest

      - name: Changelog
        uses: ardalanamini/auto-changelog@v3
        id: changelog
        with:
          github-token: ${{ github.token }}
          commit-types: |
            breaking: Breaking Changes
            feat: New Features
            fix: Bug Fixes
            revert: Reverts
            perf: Performance Improvements
            refactor: Refactors
            deps: Dependencies
            docs: Documentation Changes
            style: Code Style Changes
            build: Build System
            ci: Continuous Integration
            test: Tests
            chore: Chores
            other: Other Changes
          default-commit-type: Other Changes
          release-name: v${{ env.release_version }}
          mention-authors: true
          mention-new-contributors: true
          include-compare: true
          semver: true
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.release_version }}
          body: |
            ${{ steps.changelog.outputs.changelog }}
          prerelease: ${{ steps.changelog.outputs.prerelease }}
      - name: Prepare CD - wallet.walt.id
        run: sed "s/_DEFAULT_DEPLOYMENT_/$GITHUB_SHA/g" k8s/deployment-dev.yaml > k8s/deployment_mod.yaml
      - name: Continuous deployment - wallet.walt.id
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -n dev -f k8s/deployment_mod.yaml
      - name: Prepare CD - wallet.portal.walt.id
        run: sed "s/_DEFAULT_DEPLOYMENT_/$GITHUB_SHA/g" k8s/deployment-portal.yaml > k8s/deployment_mod.yaml
      - name: Continuous deployment - wallet.portal.walt.id
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -n dev -f k8s/deployment_mod.yaml
